spring:
  cloud:
    gateway:
      discovery:
        locator:
        enabled: true
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/auth/**
        - id: crud-service
          uri: lb://crud-service
          predicates:
            - Path=/api/v1/blogs/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**

